# Generated by Django 2.1.4 on 2019-05-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='level',
        ),
        migrations.RemoveField(
            model_name='education',
            name='year',
        ),
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
