# Generated by Django 2.1.4 on 2019-05-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0003_auto_20190516_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuser',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
