# Generated by Django 2.1.4 on 2019-05-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0004_auto_20190516_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
