# Generated by Django 2.1.4 on 2019-05-16 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0005_auto_20190516_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutuser',
            name='birth_date',
        ),
    ]
