# Generated by Django 2.1.4 on 2019-05-16 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0006_remove_aboutuser_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutuser',
            name='avi_path',
        ),
    ]
