# Generated by Django 2.1.4 on 2019-05-17 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0007_remove_aboutuser_avi_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuser',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='aboutuser',
            name='github',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutuser',
            name='linkedin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutuser',
            name='location',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='aboutuser',
            name='twitter_handle',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='aboutuser',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
