# Generated by Django 2.1.4 on 2019-05-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0008_auto_20190517_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuser',
            name='twitter_handle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
