# Generated by Django 2.1.4 on 2019-05-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0009_auto_20190518_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskills',
            name='level',
            field=models.TextField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userskills',
            name='skill',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
