# Generated by Django 2.1.4 on 2019-05-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0010_auto_20190518_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
