# Generated by Django 2.1.4 on 2019-05-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0011_education_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
