# Generated by Django 2.1.4 on 2019-05-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0012_auto_20190519_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskills',
            name='level',
        ),
    ]
