# Generated by Django 2.1.4 on 2019-05-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0013_remove_userskills_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterests',
            name='interest',
            field=models.TextField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
