# Generated by Django 2.1.4 on 2019-05-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0014_auto_20190519_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuser',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutuser',
            name='twitter_handle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
