# Generated by Django 2.1.4 on 2019-05-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0016_user_avi_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avi_path',
        ),
        migrations.AddField(
            model_name='aboutuser',
            name='avi_path',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
