# Generated by Django 2.1.4 on 2019-05-22 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0019_auto_20190521_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avi',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
