# Generated by Django 2.1.4 on 2019-05-22 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0020_auto_20190522_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avi',
            old_name='user_id',
            new_name='user',
        ),
    ]
