# Generated by Django 2.1.4 on 2019-05-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0021_auto_20190522_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='avi',
            name='delete_token',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
