# Generated by Django 2.1.4 on 2019-05-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0023_auto_20190522_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='avi',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
