# Generated by Django 2.1.4 on 2019-05-22 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0025_auto_20190522_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutuser',
            name='avi_path',
        ),
    ]
