# Generated by Django 2.1.4 on 2019-05-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0026_remove_aboutuser_avi_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuser',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aboutuser',
            name='github',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aboutuser',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aboutuser',
            name='location',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='aboutuser',
            name='twitter_handle',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
