# Generated by Django 2.1.4 on 2019-05-31 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0030_topic_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 31, 0, 38, 13, 406963)),
        ),
    ]
