# Generated by Django 2.1.4 on 2019-05-31 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0031_auto_20190531_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 31, 1, 20, 53, 249457)),
        ),
    ]
