# Generated by Django 2.1.4 on 2019-05-31 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0033_auto_20190531_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
