# Generated by Django 2.1.4 on 2019-06-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0035_auto_20190531_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
    ]
