# Generated by Django 2.1.4 on 2019-06-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0038_auto_20190612_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='timestamp',
        ),
    ]
