# Generated by Django 2.1.4 on 2019-06-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0040_reccomendation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reccomendation',
            new_name='Recommendation',
        ),
    ]
