# Generated by Django 2.1.4 on 2019-06-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0041_auto_20190613_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
