# Generated by Django 2.1.4 on 2019-06-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0042_recommendation_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
