# Generated by Django 2.1.4 on 2019-06-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0044_auto_20190619_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuser',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='aboutuser',
            name='personal',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='aboutuser',
            name='github',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='aboutuser',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='aboutuser',
            name='twitter_handle',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
