# Generated by Django 2.1.4 on 2019-06-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0045_auto_20190625_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutuser',
            old_name='twitter_handle',
            new_name='twitter',
        ),
    ]
